feature:
  - head-branch:
      - "^feature/"
      - "^feat/"

fix:
  - head-branch:
      - "^fix/"
      - "^bugfix/"
      - "^hotfix/"

docs:
  - all:
      - head-branch:
          - "^docs/"
      - changed-files:
          - any-glob-to-any-file: "**/*.md"

chore:
  - head-branch:
      - "^chore/"
      - "^build/"

refactor:
  - head-branch:
      - "^refactor/"

test:
  - any:
      - head-branch:
          - "^test/"
      - changed-files:
          - any-glob-to-any-file: "tests/**"

ci:
  - any:
      - head-branch:
          - "^ci/"
      - changed-files:
          - any-glob-to-any-file: ".github/workflows/**"

dependencies:
  - head-branch:
      - "^deps/"
      - "^dependabot/"
